# Site settings
title: Артамошкин Максим
email: admin@zverit.com
description: > # this means to ignore newlines until "baseurl:"
  Artamoshkin Maxim. Web and System software engineer. I don' t know the word «Impossible». Only «small budget» or «uninteresting job».
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zverit.com" # the base hostname & protocol for your site

# Build settings  
markdown: kramdown

encoding: utf-8

gems:
  - jekyll-sitemap


url: https://zverit.com   # with the https protocol
enforce_ssl: zverit.com   # without any protocol 
